const ActionTypes = {
    USER_SIGN_IN: "USER_SIGN_IN",
    USER_SIGN_OUT: "USER_SIGN_OUT",
    USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
    USER_SIGN_UP_FAILED: "USER_SIGN_UP_FAILED",
    USER_SIGN_IN_SUCCESS: "USER_SIGN_IN_SUCCESS",
    USER_SIGN_IN_FAILED: "USER_SIGN_IN_FAILED",
    UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
    UPDATE_USERS_LIST: "UPDATE_USERS_LIST",
    UPDATE_MESSAGES_LIST: "UPDATE_MESSAGES_LIST",
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_ERROR: "SHOW_ERROR",
    HIDE_ERROR: "HIDE_ERROR",
    SHOW_CONGRTATS: "SHOW_CONGRTATS",
    HIDE_CONGRTATS: "HIDE_CONGRTATS"
}

export default ActionTypes;